[databases]
api = host=app_data port=5432 dbname=api

[pgbouncer]
# Red e Interfaz de Escucha
listen_addr = *
listen_port = 6432

# Seguridad y Autenticación
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt

# Modos de Pooling y Dimensionamiento
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 20
min_pool_size = 5

# Compatibilidad Crítica con FastAPI (asyncpg)
max_prepared_statements = 100
track_extra_parameters = shadow_user

# Sistema y Logs
#logfile = /var/log/postgresql/pgbouncer.log
#pidfile = /var/run/postgresql/pgbouncer.pid
#admin_users = postgres